### ISSUE TITLE
helpmanual.io not available from some Ukraine's IPs

### ISSUE THREAD

**Issue by yevhen-kalyna** [samuelcolvin/helpmanual.io#10]
Hello,

From February I can't access `pydantic.helpmanual.io` and `helpmanual.io`, as I see the site available in many [countries](https://www.uptrends.com/tools/uptime), but I and a few of my friends can't access it.

From my cell network, the site is available too, but not from my internet provider.

Can you check from your side if you have some blocking for IPs `45.89.91.0` in subnet `255.255.255.128`

![image](https://user-images.githubusercontent.com/26677668/171025895-47da9cca-7597-4ccf-89ba-fab1e4a8e956.png)

**Comment by samuelcolvin** [comment]
I will check, do you mean https://pydantic-docs.helpmanual.io/ ?

**Comment by yevhen-kalyna** [comment]
Yes, this one. I will be very grateful 🙏

**Comment by samuelcolvin** [comment]
I haven't changed anything, so it must be cloudflare somehow.

What country are you in?

**Comment by yevhen-kalyna** [comment]
Ukraine, Lviv

**Comment by yevhen-kalyna** [comment]
Information from myip.ms:
![image](https://user-images.githubusercontent.com/26677668/171039298-b4801773-3371-43a9-a818-800740563c05.png)

**Comment by samuelcolvin** [comment]
So weird, I'll investigate tomorrow.

**Comment by yevhen-kalyna** [comment]
I resolved the issue. 

Using the OpenVPN client it creates an interface that has some DNS and ipv6 configurations, and its configurations broke requests to  `pydantic-docs.helpmanual.io` because it started using ipv6 at least a few months ago, or whatever, its my local problem which OpenVPN created.

Sorry for the interruption, have a good day.

**Comment by samuelcolvin** [comment]
No problem, thanks for letting me know.
