### ISSUE TITLE
Search URL

### ISSUE THREAD

**Issue by astoff** [samuelcolvin/helpmanual.io#12]
What is an URL to search a document, as in e.g. <https://docs.python.org/3/search.html?q=query>?

This is useful when setting a bookmark on a web browser etc. It would be also nice if the search works without JavaScript.

**Comment by samuelcolvin** [comment]
I'm afraid the search server isn't running anymore, it kept crashing and I stopped resetting it.

In the end, helpmanual didn't generate enough money from ads to make it worthwhile continuing work on in and fix things like this.

**Comment by astoff** [comment]
I got here through the pydantic docs. Should it perhaps be hosted in a more search-friendly place?

**Comment by samuelcolvin** [comment]
So which do you want to search? helpmanual.io is completely separate from pydantic-docs.helpmanual.io

**Comment by astoff** [comment]
The latter, I guess. So this is the repo for the website and not the engine? Sorry about that.

**Comment by samuelcolvin** [comment]
Yes.

For the pydantic docs, it's just mkdocs material, do the search is in the browser and I guess there's no easy endpoint, but you can search for others' solutions.
